---

- name: Jenkins Playbook
  gather_facts: false
  hosts: all
  become: yes
  tasks:
    - name: "apt-get update"
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: "install azure-cli pre-req"
      apt:
        name: ['ca-certificates', 'curl', 'apt-transport-https', 'lsb-release', 'gnupg']
        state: latest

#    - name: "apt-key"
#      shell:
#        cmd: "curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null"
    
    - name: download Jenkins apt-key
      get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: add Jenkins repo
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
        state: present
        filename: jenkins
      become: true


        
#    - name: "append repo"
#      shell:
#        cmd: "echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null"
    
    

    - name: "apt-get update"
      apt:
        update_cache: yes
        cache_valid_time: 86400

    #- name: "Install Jenkins"
    #  apt:
    #    name: jenkins
    #    state: latest


    - name: Install Java 11
      apt:
        name: openjdk-11-jdk
        state: present


    
    - name: Install Jenkins
      apt:
        name: jenkins
        state: latest
        update_cache: yes
      become: true

    

    - name: Install Ansible
      apt:
        name: ansible
        state: present
      become: yes  